from typing import Protocol

from iris_agent.memory.models import MemoryItem


class MemoryProvider(Protocol):
    def remember(self, content: str, session_id: str | None = None, tags: tuple[str, ...] = ()) -> MemoryItem: ...
    def search(self, query: str, session_id: str | None = None, limit: int = 4) -> list[MemoryItem]: ...
    def list(self, session_id: str | None = None) -> list[MemoryItem]: ...
    def delete(self, memory_id: str) -> None: ...
