from dataclasses import dataclass, field
from typing import Protocol
from typing import ContextManager

from iris_agent.core.models import Message


@dataclass(slots=True)
class Session:
    id: str
    name: str
    created_at: float
    updated_at: float
    messages: list[Message] = field(default_factory=list)


class SessionRepository(Protocol):
    def create(self, name: str) -> Session: ...
    def get(self, session_id: str) -> Session: ...
    def list(self) -> list[Session]: ...
    def save(self, session: Session) -> None: ...
    def append(self, session_id: str, message: Message) -> Session: ...
    def clear(self, session_id: str) -> Session: ...
    def delete(self, session_id: str) -> None: ...
    def session_lock(self, session_id: str) -> ContextManager[None]: ...
