import { useEffect, useState } from 'react';
import { approveTaskPlan, createAutomaticTaskPlan, delegateTaskStep, listSubagents, listTaskPlans, runNextTaskStep, type Subagent, type TaskPlan } from '../../api/taskPlanning';

export default function TaskPlansPage({ sessionId }: { sessionId: string }) {
  const [plans, setPlans] = useState<TaskPlan[]>([]); const [subagents, setSubagents] = useState<Subagent[]>([]); const [goal, setGoal] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { if (!sessionId) { setPlans([]); setSubagents([]); return; } try { const [tasks, agents] = await Promise.all([listTaskPlans(sessionId), listSubagents(sessionId)]); setPlans(tasks.items); setSubagents(agents.items); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : '无法加载任务计划'); } };
  useEffect(() => { void load(); }, [sessionId]);
  const perform = async (action: () => Promise<unknown>, fallback: string) => { setBusy(true); try { await action(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : fallback); } finally { setBusy(false); } };
  const createPlan = () => { const value = goal.trim(); if (value && sessionId) void perform(async () => { await createAutomaticTaskPlan(sessionId, value); setGoal(''); }, '生成计划失败'); };
  const delegate = (plan: TaskPlan, stepId: string) => { const input = window.prompt('输入允许的工具名称，用逗号分隔；留空表示不给工具权限。', ''); if (input !== null) void perform(() => delegateTaskStep(plan.id, stepId, input.split(',').map((item) => item.trim()).filter(Boolean)), '委派子 Agent 失败'); };
  return <section className="task-plans-page"><header className="task-plans-hero"><div><span>AGENT ORCHESTRATION</span><h1>任务计划控制台</h1><p>为当前会话生成计划、逐步执行，并在需要时审批后恢复。</p></div><button className="task-secondary" disabled={busy} onClick={() => void load()}>刷新</button></header>{error ? <p className="task-error">{error}</p> : null}<section className="task-create"><label htmlFor="task-goal">目标</label><div><input id="task-goal" value={goal} disabled={!sessionId || busy} onChange={(event) => setGoal(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && createPlan()} placeholder={sessionId ? '例如：收集并整理 Python 面试问答' : '请先创建或选择一个聊天会话'} /><button className="task-primary" disabled={!goal.trim() || !sessionId || busy} onClick={createPlan}>自动生成计划</button></div></section><section className="task-section"><div className="task-section-head"><h2>计划</h2><small>{plans.length} 个当前会话计划</small></div>{plans.length ? <div className="task-plan-list">{plans.map((plan) => <PlanCard key={plan.id} plan={plan} busy={busy} onRun={() => void perform(() => runNextTaskStep(plan.id), '执行步骤失败')} onApprove={(approved) => void perform(() => approveTaskPlan(plan.id, approved), '审批处理失败')} onDelegate={(stepId) => delegate(plan, stepId)} />)}</div> : <Empty text="还没有计划。输入目标后让 Agent 自动拆解步骤。" />}</section><section className="task-section"><div className="task-section-head"><h2>子 Agent</h2><small>独立会话与工具白名单</small></div>{subagents.length ? <div className="task-subagent-list">{subagents.map((agent) => <article className="task-subagent" key={agent.id}><div><strong>{agent.title}</strong><span className={`task-status is-${agent.status}`}>{agent.status}</span><p>{agent.result || agent.error || '等待执行或审批'}</p></div><small>{agent.allowed_tools.length ? agent.allowed_tools.join(' · ') : '无工具权限'}</small></article>)}</div> : <Empty text="当前会话暂无子 Agent。" />}</section></section>;
}

function PlanCard({ plan, busy, onRun, onApprove, onDelegate }: { plan: TaskPlan; busy: boolean; onRun: () => void; onApprove: (approved: boolean) => void; onDelegate: (stepId: string) => void }) {
  const waiting = plan.status === 'waiting_approval';
  return <article className="task-plan-card"><div className="task-plan-top"><div><span className={`task-status is-${plan.status}`}>{plan.status}</span><h3>{plan.goal}</h3></div>{waiting ? <div className="task-actions"><button className="task-primary" disabled={busy} onClick={() => onApprove(true)}>批准继续</button><button className="task-secondary" disabled={busy} onClick={() => onApprove(false)}>拒绝</button></div> : plan.status === 'active' ? <button className="task-primary" disabled={busy} onClick={onRun}>执行下一步</button> : null}</div><ol className="task-step-list">{plan.steps.map((step) => <li key={step.id}><div><strong>{step.title}</strong><span className={`task-status is-${step.status}`}>{step.status}</span><p>{step.instruction}</p>{step.status === 'pending' && plan.status === 'active' ? <button className="task-secondary" disabled={busy} onClick={() => onDelegate(step.id)}>委派子 Agent</button> : null}{step.result ? <p>{step.result}</p> : null}{step.error ? <p className="task-step-error">{step.error}</p> : null}</div>{step.events.length ? <details><summary>{step.events.length} 条事件</summary><ul>{step.events.slice(-5).reverse().map((event, index) => <li key={`${event.at}-${index}`}>{event.type}{event.details.tool ? ` · ${String(event.details.tool)}` : ''}{event.details.message ? ` · ${String(event.details.message)}` : ''}</li>)}</ul></details> : null}</li>)}</ol></article>;
}

function Empty({ text }: { text: string }) { return <p className="task-empty">{text}</p>; }
